# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Production

on:
  push:
    branches: [ release/production ]
  deployment:
    branches: [ release/production ]

jobs:
  Integration:
    name: Build & Integration(Prod)
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build JAR
      run: |
        gradle jar

  Deployment:
    name: Deployment(Prod)
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'deployment' }}

    steps:
      - name: Build JAR
        run: |
          gradle jar

  deployment:
    runs-on: ubuntu-latest
    environment: release/production
    concurrency: release/production

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Production Deploy
      run: |
        gradle jar

